FROM python:3.9.12

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /app
RUN mkdir /app/static
RUN mkdir /app/media

WORKDIR /app
RUN pip install --upgrade pip
ADD requirements.txt    /app/
RUN pip install -r requirements.txt

COPY . /app/
