version: '3'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command:
      - /bin/sh
      - -c
      - |
        gunicorn app.asgi:application -k \
        uvicorn.workers.UvicornWorker -b 0.0.0.0:8000
    environment:
      - DJANGO_DB_HOST=mysql
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7
    container_name: local_mysql
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    restart: unless-stopped
    platform: linux/x86_64
  redis:
    image: redis:latest
    container_name: local_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    platform: linux/x86_64
  rabbitmq:
    image: rabbitmq:3.10
    container_name: local_rabbitmq
    ports:
      - "15672:15672"
    restart: unless-stopped
    platform: linux/x86_64
  nginx:
    container_name: nginx
    build: ./compose/nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  static_volume:
  media_volume: